name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up env
        env: 
            TZ: UTC
            DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            cmake \
            tar \
            dpkg

      - name: Build
        run: |
          mkdir -p build && cd build && \
            cmake .. && \
            cmake --build . --target install
    
      - name: Create Debian Package
        env:
          VERSION: ${{  github.ref_name }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          export VERSION="${VERSION:1}"
          sudo mkdir -p /pkg/DEBIAN
          sudo chmod a+rwx -R /pkg
          echo "Package: helloworld" > /pkg/DEBIAN/control
          echo "Version: ${VERSION}" >> /pkg/DEBIAN/control
          echo "Section: base" >> /pkg/DEBIAN/control
          echo "Priority: optional" >> /pkg/DEBIAN/control
          echo "Architecture: amd64" >> /pkg/DEBIAN/control
          echo "Depends: libc6 (>= 2.15)" >> /pkg/DEBIAN/control
          echo "Requires: zstd" >> /pkg/DEBIAN/control
          echo "Maintainer: Bas Steins <debian@bascodes.com>" >> /pkg/DEBIAN/control
          echo "Description: Hello World" >> /pkg/DEBIAN/control
          mkdir -p /pkg/usr/bin 
          cp /usr/local/bin/helloworld /pkg/usr/bin/ 
          sudo chmod 0755 -R /pkg
          sudo dpkg-deb --build -Zgzip /pkg helloworld-${GITHUB_REF_NAME}.deb
          sudo chmod a+rwx helloworld-${GITHUB_REF_NAME}.deb
          cp /usr/local/bin/helloworld ./helloworld-${GITHUB_REF_NAME}

      - name: "Relase"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "helloworld-${{ github.ref_name }}.deb,helloworld-${{ github.ref_name }}"

      - name: "Make APT Repo"
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
            repo_supported_arch: |
                amd64
            repo_supported_version: |
                noble
            github_token: ${{ secrets.PAT }}
            file: helloworld-${{ github.ref_name }}.deb
            file_target_version: noble
            public_key: ${{ secrets.PUBLIC }}
            private_key: ${{ secrets.PRIVATE }}

